name: api_doc_updater
version: 0.2.0
description: Syntactic API doc updater for @source directives.
author: Patrice Chalin <pchalin@gmail.com>
homepage: https://github.com/chalin/api_doc_updater
environment:
  sdk: '>=1.14.0 <2.0.0'
dependencies:
  analyzer: ^0.29.0
  args: ^0.13.0
  collection: ^1.2.0
  path: ^1.4.0
dev_dependencies:
  test: ^0.12.0
